Added functionality to download data from API
deep-strategy/The-Architect pull request #5
Opened 2019-02-07 01:42 UTC by thiagopromano

2019-02-07 01:59 UTC, luisguilhermemsalmeida requested changes

2019-02-07 01:59 UTC, luisguilhermemsalmeida commented on app/Architect/AssetPriceProvider/AlphaVantageProvider.php
> +        $wololo = (array)HTTPRequest::get("https://www.alphavantage.co/query?function=TIME_SERIES_DAILY&symbol=$symbol&outputsize=full&apikey=" . env('ALPHAVANTAGE_KEY'));
Hey! This looks wrong!

2019-02-07 02:00 UTC, thiagopromano commented on app/Architect/AssetPriceProvider/AlphaVantageProvider.php
> +        $wololo = (array)HTTPRequest::get("https://www.alphavantage.co/query?function=TIME_SERIES_DAILY&symbol=$symbol&outputsize=full&apikey=" . env('ALPHAVANTAGE_KEY'));
q pena

2019-02-08 00:42 UTC, luisguilhermemsalmeida approved these changes

2019-02-08 00:42 UTC, merged